version: '3.7'

services:
  api:
    build: 
      context: ./
    entrypoint: bash run.sh
    restart: unless-stopped
    volumes:
    - ./:/project
    ports:
    - 8000:8000
    depends_on:
    - db
    - redis
    environment: 
      SECRET_KEY: thisisthedjangosecretkey

  db:
    image: "postgres:15"
    environment: 
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/data:/data
volumes:
  api:
  data: