apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-conf
  labels:
    tier: replicaset
spec:
  replicas: 3
  selector:
    matchLabels: # Corrected field name to matchLabels
      kind: postgres # Label to match with Pod's metadata.labels
  template:
    metadata:
      labels:
        kind: postgres # Label for the Pod's metadata.labels
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            limits:
              cpu: "1" # Limit the container to use a maximum of 1 CPU core
              memory: "512Mi" # Limit the container to use a maximum of 512 MiB of memory
            requests:
              cpu: "0.5" # Request a minimum of 0.5 CPU core for the container
              memory: "256Mi" # Request a minimum of 256 MiB of memory for the container
